---
- name: Configure Paperless Borg backup
  ansible.builtin.include_tasks: "{{ common_dir }}/configure-borg-backup.yml"
  vars:
    borg_service_name: paperless-borg
    borg_repository: "{{ paperless_borg_repository }}"
    borg_working_directory: "{{ paperless_install_path }}"
    borg_source: export

- name: Configure Paperless export service
  ansible.builtin.template:
    src: "{{ playbook_dir }}/paperless-export.service.j2"
    dest: /etc/systemd/system/paperless-export.service
    mode: "0644"
  register: paperless_export_service

- name: Configure Paperless export timer
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/paperless-export.timer"
    dest: /etc/systemd/system/paperless-export.timer
    mode: "0644"
  register: paperless_export_timer

- name: Enable Paperless export timer
  ansible.builtin.systemd_service:
    name: paperless-export.timer
    enabled: true
    daemon_reload: "{{ borg_service.changed or paperless_export_service.changed or paperless_export_timer.changed }}"
    state: "{{ 'restarted' if paperless_export_timer.changed else 'started' }}"
