---
- name: Configure Paperless kernel settings
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-paperless.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      vm.overcommit_memory = 1
  register: paperless_sysctl_config

- name: Apply Paperless kernel settings
  ansible.builtin.command:
    argv:
      - sysctl
      - -p
      - /etc/sysctl.d/99-paperless.conf
  when: paperless_sysctl_config.changed
