all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: /root/.ssh/ansible
    ansible_python_interpreter: /usr/bin/python3
    github_ssh_user: sargant

  hosts:
    tailscale:
      ansible_host: tailscale.home.arpa

    print_server:
      ansible_host: print-server.home.arpa
